#!/bin/bash

COUCHDB_USER=${COUCHDB_USER:-admin}
COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
COUCH_CONFIG=/opt/couchdb/etc
HEADLESS_SERVICE_NAME=${HEADLESS_SERVICE_NAME:-couchdb-internal}
NAMESPACE=${NAMESPACE:-`cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`}

echo "-name couchdb@${POD_NAME}.${HEADLESS_SERVICE_NAME}.${NAMESPACE}.svc.cluster.local" >> $COUCH_CONFIG/vm.args

echo -e "[admins]\n${COUCHDB_USER} = ${COUCHDB_PASSWORD}" >  $COUCH_CONFIG/local.d/admin.ini

if [[ "$DELAYED_COMMITS" != "false" ]]; then
cat <<DELAYED_COMMITS >$COUCH_CONFIG/local.d/delayed_commits.ini
[couchdb]
delayed_commits = true
DELAYED_COMMITS
fi

N=${N:-1}
Q=${Q:-8}

cat <<DOCUMENT_COPIES >$COUCH_CONFIG/local.d/sharding.ini
[cluster]
n=$N
q=$Q
DOCUMENT_COPIES

chown -LR couchdb:couchdb /opt/couchdb
echo "Exit code from chown: $?"

su -m couchdb -c /opt/couchdb/bin/couchdb $*
